### ISSUE TITLE
Fatal Error (Duplicate function declaration) accessing settings page

### ISSUE THREAD

**Issue by dg-jparmenter** [rosell-dk/webp-express#186] opened 2019-02-23 21:37 UTC
This occurs directly after a fresh install/activation with v0.11.3:

[Sat Feb 23 13:24:12 2019] [warn] [client 64.147.29.34] mod_fcgid: stderr: PHP Fatal error:  Cannot redeclare webp_express_add_inline_script() (previously declared in /var/www/vhosts/<foo>/httpdocs/wp-content/plugins/webp-express/lib/options/enqueue_scripts.php:11) in /var/www/vhosts/<foo>/httpdocs/wp-content/plugins/webp-express/lib/options/enqueue_scripts.php on line 11, referer: https://<foo>/wp-admin/plugins.php?plugin_status=all&paged=1&s

I cannot access the settings page without manually changing this enqueue_scripts file.  Wrapping this function in a simple if ( ! function_exists() )  resolves it.  

I'm on a shared environment and none of the local conversion methods are available.   I am running a pretty basic theme; also W3TC. Happy to provide additional details about the environment for debugging.

**Comment by rosell-dk** [comment] 2019-02-25 09:26
It seems that this could only happen if the `admin_init` hook is fired multiple times. So that is odd. That hook ought only to be called once. However, it has happened to others that the `admin_init` hooked has been fired multiple times: https://stackoverflow.com/questions/30476213/wordpress-admin-init-hook-being-called-multiple-times.

Of course I shall implement your fix so the plugin doesn't fail when a site is in the unfortunate situation that the hook under some circumstances are fired multiple times. But this issue calls for a further investigation. We should try to find out what is causing those extra fires. It might be an ill-behaving plugin or theme (it might even be WebP Express). Having that in your system is a potential bomb. Not only to your site, but to any site that uses that plugin or theme.

**Comment by rosell-dk** [comment] 2019-02-25 09:45
I have tried to run activation but I do not experience the problem. I also tested with no converters being available, still no luck in reproducing. Can you give me some more info about your environment? What is your Wordpress version? 
Could you try to see if the error happens with standard Wordpress theme? 
And could you try to deactivate all plugins and see the error still happens when activating WebP Express?

**Comment by rosell-dk** [comment] 2019-02-27 11:44
As nobody has reported this before, the multiple firing of the `admin_init` hook is probably not caused by WebP Express. Closing

**Closed by rosell-dk** 2019-02-27 11:44 UTC
