### ISSUE TITLE
Wordfence Blocked for LFI & performance enhancement 

### ISSUE THREAD

**Issue by cantoute** [rosell-dk/webp-express#94] opened 2018-12-06 14:01 UTC
Wordfence firewall gets offended by the rewrite rule:

Blocked for LFI: Local File Inclusion in query string: source=/var/www/[...].jpg

And at same time calling php to deliver the image is a killer performance wise

I understand that php is called just to filter out cases where .web version is larger than the original.

Perhaps it would be possible to have an empty file (touch) next to the .webp in case it is bigger
Exemple:
wp-content/webp-express/webp-images/doc-root/wp-content/uploads/[...]/myImage.webp.isBigger

and use it in the rewrite rule

This way we could have image sent without calling php, gaining ~100ms on calls and avoid offending wordfence.

I would be happy to look into implementing this unless I'm missing out something else.

Thanks for your great job :)

**Comment by rosell-dk** [comment] 2018-12-06 19:47
Hi cantoute,

In short: Yes, I know :)

The LFI warning has its own issue here:
https://github.com/rosell-dk/webp-express/issues/87
It seems that the problem is only for the test-run script - thats where the source parameter is transfered in querystring. It is easily dealt with, because the test-run script really don't need the flexibility of being able to test-run different source files.

I'm also aware that it is not optimal to invoke php for every image request, and it will be better with a redirect rule. I do however not have any numbers on this, or any idea *how* bad it is. You are right that using mod_rewrite to serve existing files introduces a a little issue about the possibility of the converted files being larger than the original. And I actually imagined a solution as you described. However, it seems the risk for webp files becoming larger than the original files is quite small, so I deem it is no real issue. It is two other worries that have held me back. Or rather - made me remove the rules in I think it was version 0.3 - but with the intention of putting it back, as an optional feature - when I felt ready.

1: I wanted 0.3 to be rock-steady. The rewrite rules added complexity. By removing the complexity, I decreased risks of bugs. And I also ensured that bugs in the php library would not hide as easily. Although routing to an existing file is quite easy, adding Vary header and making it work in Litespeed made complexity grow, as witnessed here: https://github.com/rosell-dk/webp-convert/blob/master/docs/webp-on-demand/tweaks.md. 

2: There is the issue that the source file may be edited. The library checks modified dates, but I do not think that is possible in .htaccess. I did not wish to have anyone complaining about that they edited the image, but the webp image is still the old one.

Making it an optional feature has the benefit that it allows a little help text explaining the pros and cons. And I guess that the latter issue is ok, as long as the user makes the conscious choice. After all, allowing images to be cached presents the same dilemma.

The issue about original files changing could be dealt with a clean-up script running regularly, simply deleting the webp images which are older than their original counterpart.

I appreciate that you'd like to help with the development. But maybe we can keep it on an idea-based level in the next couple of weeks? There are some other issues on the roadmap I'd like to focus on first. And also, I have refactored WebP Convert, but is not quite through. The refactoring work is in the 2.0 branch. I'd like to get that work done as well, before adding new features to WebP Convert. Or at least have it stable enough for you to work on.

**Comment by cantoute** [comment] 2018-12-06 20:23
Hi,

Thanks for your detailed answer.
Your point (2) about media being edited (or deleted) should be manageable using hooks... 'wp_save_image_editor_file' ?
In a .htaccess at my knowledge this could only be achieved via a .map file... that would need to be updated and that doesn't make things easier.

> The issue about original files changing could be dealt with a clean-up script running regularly, simply deleting the webp images which are older than their original counterpart.

I would go more for a button that does the call rather then a cron... on big libraries can be a killer.

Perhaps even a "clear all cache" would be nice too (++easy) (as I discovered that gd compressed webp where no way as light as those built by cwebp... I manually deleted all .webp)

As you suggest, making it an optional feature as you recommend seems like the way to go, but on height trafic sites, it's a needed feature.

One could say that if you have such trafic might as well use a CDN that does the webp on the fly.  Here I run wordpress behind a local varnish and it works really nice (with features like serving a stalled/kept content in case of 5xx errors that most CDN don't offer) but I haven't implemented yet a way to serve different cached image based on webp capability, so every image call is passed to the backend.

I'll have a look at 2.0 branch :)

**Comment by cantoute** [comment] 2018-12-06 20:35
As a temporary workaround, it's possible to disable the LFI rule from the firewall

Wordfence -> Firewall -> Manage WAF -> Rules

Find the line "LFI: Local File Inclusion"

**Comment by cantoute** [comment] 2018-12-06 22:02
This is what I've added to my wp-content/.htaccess (before Web Express rules) to get a direct cache deliver and bypass php call

```apache
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTP_ACCEPT} image/webp
  RewriteCond %{REQUEST_FILENAME} -f
  RewriteCond %{REQUEST_URI} ([^?]*)
  RewriteCond %{DOCUMENT_ROOT}/wp-content/webp-express/webp-images/doc-root%1.webp -f
  # as cache file exists, no need to check if option allows .png conversion in webp express
  RewriteRule \.(jpe?g|png)(\?|$) /wp-content/webp-express/webp-images/doc-root%1.webp [NC,T=image/webp,L]
</IfModule>

<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType image/webp "access plus 2 weeks"
</IfModule>

#BEGIN WebP Express
[...]
```

**Comment by rosell-dk** [comment] 2018-12-07 18:07
Yes, hooking up to image save / delete hooks is a good idea :)

**Comment by rosell-dk** [comment] 2018-12-07 18:10
Rewriting the request to point to the existing webp does not solve the Wordfence block, as it only works when there already is a webp file. The plugin doesn't bulk convert, but converts when needed (when there aren't already a converted file)

**Comment by cantoute** [comment] 2018-12-07 18:23
Yes I know...
but to get the %{REQUEST_FILENAME} without %{DOCUMENT_ROOT}
`RewriteCond %{REQUEST_URI} ^([^?]*)` did the job

**Comment by cantoute** [comment] 2018-12-07 18:42
For those no so familiar with regex
This line protects agains calls like 
`/wp-content/.jpg` or `/wp-content/some/folder.jpg/file.anything`

`RewriteRule [^/]+\.(jpe?g|png)(\?|$) /wp-content/webp-express/webp-images/doc-root%1.webp [NC,T=image/webp,L]`

It's a wild world out there... It's a good practice not to leave any gaps

**Comment by rosell-dk** [comment] 2018-12-07 20:33
It seems you might as well use %{REQUEST_URI} directly in the RewriteRule instead of %1 ?

I'm surprised to discover that REQUEST_URI actually seems to be the relative file path from %{DOCUMENT_ROOT} to %{REQUEST_FILENAME}. Isn't it supposed to be an URL path rather than a file path? I mean, shouldn't it be the URL shown in the browser? These are not necessarily the same. If one for example "give wordpress its own directory" using method 1 [described here](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory), the path in the URL (shown in the location bar) will not be the same as the file path.

**Comment by rosell-dk** [comment] 2018-12-07 20:35
I'm cautiously delighted!
I do not trust %{REQUEST_URI} completely. I used it to begin with, but switched to %{SCRIPT_FILENAME}. I seem to remember it behaving slightly different in Litespeed.

**Comment by cantoute** [comment] 2018-12-07 22:46
and if REQUEST_URI shows differences in Litespeed why not deal with it in the php?
But of what I could find, shouldn't be different as it is the header the server receives that is passed here

Host: example.com
GET /some/path?blabla&blabla

%{REQUEST_URI} is what comes on the GET line (or POST|PUT|etc...)

**Comment by cantoute** [comment] 2018-12-07 22:54
An other way would be to change what you pass as a GET param to be part of the path_info
Changing
`RewriteRule ^(.*)\.(jpe?g|png)$ /wp-content/plugins/webp-express/wod/webp-on-demand.php?source=%{SCRIPT_FILENAME}&wp-content=wp-content&%1 [NC,L]`
to
`RewriteRule ^(.*)\.(jpe?g|png)$ /wp-content/plugins/webp-express/wod/webp-on-demand.php/%{SCRIPT_FILENAME} [NC,L]`

**Comment by cantoute** [comment] 2018-12-07 22:59
And this is wordpress world... anyone trying to run it out of LAMP env is going to face issue, no matter what you do!

**Comment by rosell-dk** [comment] 2018-12-08 19:06
True, if there is a difference in REQUEST_URI, and we simply pass it to the PHP, it can be dealt with in the PHP. I have a vague memory of something with the leading dash not being there under some circumstances.
Anyway, it seems REQUEST_URI is a bit more tricky to work with than %{SCRIPT_FILENAME}.

**Comment by rosell-dk** [comment] 2018-12-10 10:32
Closing this issue, as I have created new issues for what needs to be done (#98 and #100)

**Closed** 2018-12-10 10:33 UTC
